# Generated by Django 5.2.8 on 2025-11-21 19:05

from django.db import migrations


HALL_NAMES = ["Зал №1", "Зал №2", "Зал №3"]
PLACE_CODES = ["A1", "A2", "A3", "B1", "B2", "B3", "B4"]


def seed_rooms_and_places(apps, schema_editor):
    Room = apps.get_model('tickit', 'Room')
    Place = apps.get_model('tickit', 'Place')

    for name in HALL_NAMES:
        room, _ = Room.objects.get_or_create(name=name)
        for code in PLACE_CODES:
            Place.objects.get_or_create(room=room, code=code)


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_rooms_and_places, migrations.RunPython.noop),
    ]
